config/routes.rb
Cp2::Application.routes.draw do
  resources :points do
    collection do
      get 'range'
    end
  end
 

  resources :jobs

  resources :distance_matrix_entries
  match 'distance_matrix_entries/:id/polyline', to: 'distance_matrix_entries#get_polyline', :via => :get
  match 'distance_matrix_entries/:id', to: 'distance_matrix_entries#update_tag', :via => :post
  resources :distance_matrices

  resources :tracksegments #, :only => [:index, :show]

  resources :tracks, :except => [:new]

  match '/explore' => 'root#explore', :via => :get
  match '/search' => 'root#search', :via => :get
  match '/heatmap' => 'root#heatmap', :via => :get
  match '/api/completeJob' => 'api#completeJob', :via => :post
  match '/api/getJobs' => 'api#getJobs', :via => :get
  match '/api/reset' => 'api#reset', :via => :get  

  get '/tracksegments/:id/points', to: 'tracksegments#tracksegment_points'
  get '/tracksegments/:id/points/index', to: 'tracksegments#find_point'

  root 'root#index'

end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :tracksegment  

  def as_json(options={})
    super(:only => [:lat, :lon])
  end
  def to_s 
  	return "[".concat(self.lat.to_s).concat(",").concat(self.lon.to_s).concat(",").concat(self.recorded_at.to_s).concat("]")
  end
  def latlng
    [self.lat ,self.lon]
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.find(:all, :limit => 100)
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  #GET /points/range?start=<>&end=<>
  def range 
    if(params.has_key?(:start) and params.has_key?(:end))
      s = params[:start].to_i
      e = params[:end].to_i
      

      points = Point.where('id >= ? AND id <= ?', s, e)
      render :json => points.to_json
    else
      render :json => '[]'
    end
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render action: 'show', status: :created, location: @point }
      else
        format.html { render action: 'new' }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:lat, :lon, :timestamp, :tracksegment_id)
    end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :tracksegment %><br>
    <%= f.text_field :tracksegment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Listing points</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Timestamp</th>
      <th>Tracksegment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.id %></td>
        <td><%= point.lat %></td>
        <td><%= point.lon %></td>
        <td><%= point.recorded_at %></td>
        <td><%= point.tracksegment.id %></td>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @point.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @point.lon %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @point.recorded_at %>
</p>

<p>
  <strong>Tracksegment:</strong>
  <%= @point.tracksegment %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>