config/routes.rb
Cp2::Application.routes.draw do
  resources :points do
    collection do
      get 'range'
    end
  end
 

  resources :jobs

  resources :distance_matrix_entries
  match 'distance_matrix_entries/:id/polyline', to: 'distance_matrix_entries#get_polyline', :via => :get
  match 'distance_matrix_entries/:id', to: 'distance_matrix_entries#update_tag', :via => :post
  resources :distance_matrices

  resources :tracksegments #, :only => [:index, :show]

  resources :tracks, :except => [:new]

  match '/explore' => 'root#explore', :via => :get
  match '/search' => 'root#search', :via => :get
  match '/heatmap' => 'root#heatmap', :via => :get
  match '/api/completeJob' => 'api#completeJob', :via => :post
  match '/api/getJobs' => 'api#getJobs', :via => :get
  match '/api/reset' => 'api#reset', :via => :get  

  get '/tracksegments/:id/points', to: 'tracksegments#tracksegment_points'
  get '/tracksegments/:id/points/index', to: 'tracksegments#find_point'

  root 'root#index'

end

app/controllers/distance_matrices_controller.rb
class DistanceMatricesController < ApplicationController
  before_action :set_distance_matrix, only: [:show, :edit, :update, :destroy]

  # GET /distance_matrices
  # GET /distance_matrices.json
  def index
    @distance_matrices = DistanceMatrix.all
  end

  # GET /distance_matrices/1
  # GET /distance_matrices/1.json
  def show        
  end

  # GET /distance_matrices/new
  def new
    @distance_matrix = DistanceMatrix.new
  end

  # GET /distance_matrices/1/edit
  def edit
  end

  # POST /distance_matrices
  # POST /distance_matrices.json
  def create
    @distance_matrix = DistanceMatrix.new(distance_matrix_params)

    respond_to do |format|
      if @distance_matrix.save
        format.html { redirect_to @distance_matrix, notice: 'Distance matrix was successfully created.' }
        format.json { render action: 'show', status: :created, location: @distance_matrix }
      else
        format.html { render action: 'new' }
        format.json { render json: @distance_matrix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distance_matrices/1
  # PATCH/PUT /distance_matrices/1.json
  def update
    respond_to do |format|
      if @distance_matrix.update(distance_matrix_params)
        format.html { redirect_to @distance_matrix, notice: 'Distance matrix was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @distance_matrix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distance_matrices/1
  # DELETE /distance_matrices/1.json
  def destroy
    @distance_matrix.destroy
    respond_to do |format|
      format.html { redirect_to distance_matrices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distance_matrix
      @distance_matrix = DistanceMatrix.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distance_matrix_params
      params[:distance_matrix]
    end
end

app/helpers/distance_matrices_helper.rb
module DistanceMatricesHelper
end

app/views/distance_matrices/_form.html.erb
<%= form_for @distance_matrix, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                distance_matrices_path, :class => 'btn' %>
  </div>
<% end %>

app/views/distance_matrices/edit.html.erb
<%- model_class = DistanceMatrix -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/distance_matrices/index.html.erb
<%- model_class = DistanceMatrix -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @distance_matrices.each do |distance_matrix| %>
      <tr>
        <td><%= link_to distance_matrix.id, distance_matrix_path(distance_matrix) %></td>
        <td><%=l distance_matrix.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_distance_matrix_path(distance_matrix), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      distance_matrix_path(distance_matrix),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_distance_matrix_path,
            :class => 'btn btn-primary' %>

app/views/distance_matrices/new.html.erb
<%- model_class = DistanceMatrix -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/distance_matrices/show.html.erb
<%- model_class = DistanceMatrix -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:trackseg) %>:</strong></dt>
    <dd><%= link_to @distance_matrix.tracksegment.id, tracksegment_path(@distance_matrix.tracksegment) %></dd>
  </dt>
<% if @distance_matrix.entries.empty? %>
</dl>
<% else %>
  <dt><strong><%= model_class.human_attribute_name(:entries) %>:</strong></dt>
  <dd>
    <% entries = @distance_matrix.entries %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th>CPDur</th>
          <th>CPDist</th>          
          <th>GDur</th>
          <th>GDist</th>         

              
        </tr>
      </thead>
      <tbody>
        <% entries.each do |entry| %>
          <tr>
            <td><%= link_to entry.id, distance_matrix_entry_path(entry) %></td>
            <td><%= entry.cp_duration_in_seconds %></td>
            <td><%= entry.cp_distance_in_km %></td>                
            <td><%= entry.duration_in_seconds %></td>
            <td><%= entry.distance_in_km %></td>                
            
            
          </tr>
        <% end %>
      </tbody>
    </table>
  </dd>
  </dl>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              distance_matrices_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_distance_matrix_path(@distance_matrix), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              distance_matrix_path(@distance_matrix),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>