config/routes.rb
Cp2::Application.routes.draw do
  resources :points do
    collection do
      get 'range'
    end
  end
 

  resources :jobs

  resources :distance_matrix_entries
  match 'distance_matrix_entries/:id/polyline', to: 'distance_matrix_entries#get_polyline', :via => :get
  match 'distance_matrix_entries/:id', to: 'distance_matrix_entries#update_tag', :via => :post
  resources :distance_matrices

  resources :tracksegments #, :only => [:index, :show]

  resources :tracks, :except => [:new]

  match '/explore' => 'root#explore', :via => :get
  match '/search' => 'root#search', :via => :get
  match '/heatmap' => 'root#heatmap', :via => :get
  match '/api/completeJob' => 'api#completeJob', :via => :post
  match '/api/getJobs' => 'api#getJobs', :via => :get
  match '/api/reset' => 'api#reset', :via => :get  

  get '/tracksegments/:id/points', to: 'tracksegments#tracksegment_points'
  get '/tracksegments/:id/points/index', to: 'tracksegments#find_point'

  root 'root#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :distance_matrix_entry, :foreign_key => 'distance_matrix_entry_id', :dependent => :destroy

  def as_json(options={})
    super(:only => [:id], 
      :include => 
      { 
        :distance_matrix_entry => 
        { 
          :only => [],
          :include => 
          {
            :origin => {:only => [:lat, :lon]},
            :dest => {:only => [:lat, :lon]}
          }
        }
      }
    )
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  def index
    @jobs = Job.find(:all, :limit => 100)
  end

  # GET /jobs/1
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /jobs/1
  def update
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def job_params
      params[:job]
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :pending, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pending, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :processed, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :processed, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :worker_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :worker_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :completed_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :completed_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :distance_matrix_entry_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :distance_matrix_entry_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                jobs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pending) %></th>
      <th><%= model_class.human_attribute_name(:processed) %></th>
      <th><%= model_class.human_attribute_name(:worker_id) %></th>
      <th><%= model_class.human_attribute_name(:completed_at) %></th>
      <th><%= model_class.human_attribute_name(:distance_matrix_entry_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.pending %></td>
        <td><%= job.processed %></td>
        <td><%= job.worker_id %></td>
        <td><%= job.completed_at %></td>
        <td><%= link_to job.distance_matrix_entry_id, distance_matrix_entry_path(job.distance_matrix_entry_id) %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pending) %>:</strong></dt>
  <dd><%= @job.pending %></dd>
  <dt><strong><%= model_class.human_attribute_name(:processed) %>:</strong></dt>
  <dd><%= @job.processed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:worker_id) %>:</strong></dt>
  <dd><%= @job.worker_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:completed_at) %>:</strong></dt>
  <dd><%= @job.completed_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:distance_matrix_entry_id) %>:</strong></dt>
  <dd><%= @job.distance_matrix_entry_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              jobs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>