config/routes.rb
Cp2::Application.routes.draw do
  resources :points do
    collection do
      get 'range'
    end
  end
 

  resources :jobs

  resources :distance_matrix_entries
  match 'distance_matrix_entries/:id/polyline', to: 'distance_matrix_entries#get_polyline', :via => :get
  match 'distance_matrix_entries/:id', to: 'distance_matrix_entries#update_tag', :via => :post
  resources :distance_matrices

  resources :tracksegments #, :only => [:index, :show]

  resources :tracks, :except => [:new]

  match '/explore' => 'root#explore', :via => :get
  match '/search' => 'root#search', :via => :get
  match '/heatmap' => 'root#heatmap', :via => :get
  match '/api/completeJob' => 'api#completeJob', :via => :post
  match '/api/getJobs' => 'api#getJobs', :via => :get
  match '/api/reset' => 'api#reset', :via => :get  

  get '/tracksegments/:id/points', to: 'tracksegments#tracksegment_points'
  get '/tracksegments/:id/points/index', to: 'tracksegments#find_point'

  root 'root#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CrowdPath</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= google_maps_api %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <title><%= content_for?(:title) ? yield(:title) : "CrowdPath" %></title>
    <%= csrf_meta_tags %>
  </head>
  <body>

     <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand">CrowdPath</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Search", root_path %></li>                    
              <li><%= link_to "Explore", explore_path %></li>                    
              <li><%= link_to "Heat Map", heatmap_path %></li>
              <li><%= link_to "Upload", tracks_path %></li>                                  
              <li> <h4>-- Refresh page if map fails to load -- </h4></li>
            </ul>

          </div>
          
        <form class="loginBox navbar-search pull-right" action="/distance_matrix_entries" method="get">          
          <input type="text" name="id" class="search-query span2" placeholder="Entry Search">   
        </form>
        
        </div>

      </div>
    </div>
     <script>  
         $(function() {
        $('form').each(function() {
            $('input').keypress(function(e) {
                // Enter pressed?
                if(e.which == 10 || e.which == 13) {
                    this.form.submit();
                }
            });

            
        });
    });
    </script>
    <div class="container">
      <%= yield %>
    </div>
    

   

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

  </body>
</html>